# Inspired by https://github.com/mbentley/docker-timemachine#example-usage-for-smb
version: '3.3'

services:
  timemachine:
    container_name: timemachine
    image: 'mbentley/timemachine:smb'
    restart: unless-stopped
    network_mode: host
    # If enabling ports, disable network_mode=host
    # ports:
    #     - '137:137/udp'
    #     - '138:138/udp'
    #     - 139:139
    #     - 445:445
    environment:
      # - ADVERTISED_HOSTNAME=${TM_SHARENAME} # Unclear what this does. but it breaks the build
      - CUSTOM_SMB_CONF=false
      - CUSTOM_USER=false
      - DEBUG_LEVEL=1
      - MIMIC_MODEL=TimeCapsule8,119
      # - EXTERNAL_CONF=/path/to/external/conf/file # => https://github.com/mbentley/docker-timemachine#example-external_conf-file
      - HIDE_SHARES=no
      - TM_USERNAME=timemachine
      - TM_GROUPNAME=timemachine
      - TM_UID=1000
      - TM_GID=1000
      - PASSWORD=${TM_PASSWORD:-timemachine}
      - SET_PERMISSIONS=false
      - SHARE_NAME=${TM_SHARENAME:-TimeMachine}
      - SMB_INHERIT_PERMISSIONS=no
      - SMB_NFS_ACES=yes
      - SMB_METADATA=stream
      - SMB_PORT=445
      - SMB_VFS_OBJECTS=acl_xattr fruit streams_xattr
      - VOLUME_SIZE_LIMIT=${TM_DEVICE_SIZE_MB} MB
      - WORKGROUP=WORKGROUP
    volumes:
      # NOTE: /path/to/mounted/volume:/opt/timemachine
      - '${TM_DEVICE_MOUNT_POINT}:/opt/timemachine'
      - 'var-lib-samba:/var/lib/samba'
      - 'var-cache-samba:/var/cache/samba'
      - 'run-samba:/run/samba'

volumes:
  var-lib-samba:
  var-cache-samba:
  run-samba:
