name: yamllint
on: [push, pull_request]

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4

      - name: 🚀 Run yamllint
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          file_or_dir: docker-compose.yml
